package com.wolf.shoot.service.excel;
// This file is auto generated by xls2script tools.
// Any modification will be covered.

public class Bullet {

    private int        ID;        // 编号
    private String     name;      // 名称
    private String     desc;      // 描述
    private String     className;     // 游戏类
    private int        model;     // 模型id
    private float      attackRate; // 伤害系数
    private float      imbibeRate; // 吸血系数
    private float      moveSpeed; // 移动速度
    private float      life;      // 存活时间
    private int        lvl;       // 等级
    private boolean    penetrate; // 是否贯穿
    private boolean    track;     // 是否追随
    private float      trackAngleSpeed; // 追随角速度
    private String     hitEffect; // 命中特效
    private String     deadEffect; // 消散特效
    private String     shakeParam; // 震屏参数
    private boolean    inheritSpeed; // 是否继承速度
    private float      accelerate; // 加速度
    private float      accStartTime; // 加速度开始时间
    private float      accDuration; // 加速度持续时间
    private float      tSpeed;    // 切线移动速度
    private float      tAccelerate; // 切线加速度
    private float      tAccStartTime; // 切线加速度开始时间
    private float      tAccDuration; // 切线加速度持续时间
    private float      angleSpeed; // 角速度
    private int        exploseSkill; // 爆炸触发技能

    public int getID() {
        return ID;
    }
    public void setID(int _ID) {
        ID = _ID;
    }

    public String getName() {
        return name;
    }
    public void setName(String _name) {
        name = _name;
    }

    public String getDesc() {
        return desc;
    }
    public void setDesc(String _desc) {
        desc = _desc;
    }

    public int getModel() {
        return model;
    }
    public void setModel(int _model) {
        model = _model;
    }

    public float getAttackRate() {
        return attackRate;
    }
    public void setAttackRate(float _attackRate) {
        attackRate = _attackRate;
    }

    public float getImbibeRate() {
        return imbibeRate;
    }
    public void setImbibeRate(float _imbibeRate) {
        imbibeRate = _imbibeRate;
    }

    public float getMoveSpeed() {
        return moveSpeed;
    }
    public void setMoveSpeed(float _moveSpeed) {
        moveSpeed = _moveSpeed;
    }

    public float getLife() {
        return life;
    }
    public void setLife(float _life) {
        life = _life;
    }

    public int getLvl() {
        return lvl;
    }
    public void setLvl(int _lvl) {
        lvl = _lvl;
    }

    public boolean getPenetrate() {
        return penetrate;
    }
    public void setPenetrate(boolean _penetrate) {
        penetrate = _penetrate;
    }

    public boolean getTrack() {
        return track;
    }
    public void setTrack(boolean _track) {
        track = _track;
    }

    public float getTrackAngleSpeed() {
        return trackAngleSpeed;
    }
    public void setTrackAngleSpeed(float _trackAngleSpeed) {
        trackAngleSpeed = _trackAngleSpeed;
    }

    public String getHitEffect() {
        return hitEffect;
    }
    public void setHitEffect(String _hitEffect) {
        hitEffect = _hitEffect;
    }

    public String getDeadEffect() {
        return deadEffect;
    }
    public void setDeadEffect(String _deadEffect) {
        deadEffect = _deadEffect;
    }

    public String getShakeParam() {
        return shakeParam;
    }
    public void setShakeParam(String _shakeParam) {
        shakeParam = _shakeParam;
    }

    public boolean getInheritSpeed() {
        return inheritSpeed;
    }
    public void setInheritSpeed(boolean _inheritSpeed) {
        inheritSpeed = _inheritSpeed;
    }

    public float getAccelerate() {
        return accelerate;
    }
    public void setAccelerate(float _accelerate) {
        accelerate = _accelerate;
    }

    public float getAccStartTime() {
        return accStartTime;
    }
    public void setAccStartTime(float _accStartTime) {
        accStartTime = _accStartTime;
    }

    public float getAccDuration() {
        return accDuration;
    }
    public void setAccDuration(float _accDuration) {
        accDuration = _accDuration;
    }

    public float getTSpeed() {
        return tSpeed;
    }
    public void setTSpeed(float _tSpeed) {
        tSpeed = _tSpeed;
    }

    public float getTAccelerate() {
        return tAccelerate;
    }
    public void setTAccelerate(float _tAccelerate) {
        tAccelerate = _tAccelerate;
    }

    public float getTAccStartTime() {
        return tAccStartTime;
    }
    public void setTAccStartTime(float _tAccStartTime) {
        tAccStartTime = _tAccStartTime;
    }

    public float getTAccDuration() {
        return tAccDuration;
    }
    public void setTAccDuration(float _tAccDuration) {
        tAccDuration = _tAccDuration;
    }

    public float getAngleSpeed() {
        return angleSpeed;
    }
    public void setAngleSpeed(float _angleSpeed) {
        angleSpeed = _angleSpeed;
    }

    public int getExploseSkill() {
        return exploseSkill;
    }
    public void setExploseSkill(int _exploseSkill) {
        exploseSkill = _exploseSkill;
    }


};
