/*
 * Server基本信息
 */
config.serverType=world;
config.charset="UTF-8";
config.version="0.2.0.1";
config.serverId="8001";
config.bindIp="0.0.0.0";
config.ports="7090";
config.serverName="OnLine";
config.language="zh_CN";
config.i18nDir="i18n";
config.gameId="shoot";
config.developModel= 1;
config.tcpMessageQueueDirectDispatch=true;
/**gameexcutor配置***/
config.gameExcutorCorePoolSize=2;
config.gameExcutorKeepAliveTime=60;
config.gameExcutorCycleTime=1000;
config.gameExcutorMinCycleTime=1000;
config.updateServiceExcutorFlag=true;
/**udp配置***/
config.updPorts="10090";
config.updQueueMessageProcessWorkerSize=1;
config.udpMessageOrderQueueFlag=true;
/**rpc配置*/
config.rpcFlag=true;
//这个是提供外网使用的，请使用外网地址
config.rpcBindIp="127.0.0.1";
config.rpcPorts="10100";
config.rpcThreadPoolSize=60;
config.rpcThreadPoolQueueSize=65536;
config.rpcConnectThreadSize=16;
config.rpcSendProxyThreadSize=16;
config.rpcServicePackage="com.wolf.shoot.service.rpc.service.server";
/**message**/
config.netMessageHandlerNameSpace="com.wolf.shoot.message.handler.impl";
config.netMsgNameSpace="com.wolf.shoot.message.logic";
